package org.example.basicfhirserver.config;

import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.rest.server.RestfulServer;
import ca.uhn.fhir.rest.server.interceptor.RequestValidatingInterceptor;
import org.example.basicfhirserver.interceptor.CustomSecurityInterceptor;
import org.example.basicfhirserver.provider.EncounterResourceProvider;
import org.example.basicfhirserver.provider.ObservationResourceProvider;
import org.example.basicfhirserver.provider.PatientResourceProvider;
import org.example.basicfhirserver.provider.PractitionerResourceProvider;
import org.hl7.fhir.r4.model.CanonicalType;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;
import java.util.List;


@Configuration
public class FhirServerConfig {

    @Bean
    public ServletRegistrationBean<RestfulServer> fhirServerServlet(
            PatientResourceProvider patientResourceProvider,
            ObservationResourceProvider observationResourceProvider,
            EncounterResourceProvider encounterResourceProvider,
            PractitionerResourceProvider practitionerResourceProvider,
            FhirContextConfig fhirContextConfig,
            RequestValidatingInterceptor validatingInterceptor) {

        FhirContext ctx = fhirContextConfig.fhirContext();
        RestfulServer servlet = new RestfulServer(ctx);

        servlet.setResourceProviders(List.of(
                patientResourceProvider,
                observationResourceProvider,
                encounterResourceProvider,
                practitionerResourceProvider
        ));

//      RequestValidatingInterceptor valInterceptor = getValInterceptor(ctx);
        CustomSecurityInterceptor customSecurityInterceptor = new CustomSecurityInterceptor();

        // 🛠️ CUSTOM METADATA OVERRIDE
        // This gives you direct access to fine-tune the auto-generated CapabilityStatement
        ca.uhn.fhir.rest.server.provider.ServerCapabilityStatementProvider metadataProvider = new ca.uhn.fhir.rest.server.provider.ServerCapabilityStatementProvider(servlet) {
            @Override
            public org.hl7.fhir.r4.model.CapabilityStatement getServerConformance(jakarta.servlet.http.HttpServletRequest theRequest, ca.uhn.fhir.rest.api.server.RequestDetails theRequestDetails) {

                // 1. Fetch the default statement generated by HAPI scanning
                org.hl7.fhir.r4.model.CapabilityStatement cs = (org.hl7.fhir.r4.model.CapabilityStatement) super.getServerConformance(theRequest, theRequestDetails);

                // 2. Customize top-level company/project metrics
                cs.setPublisher("My Premium Healthcare Facade Platform");
                cs.setName("US-Core-Compliant-Facade-Engine");

                List<CanonicalType> supportedIGList = new ArrayList<>();
                supportedIGList.add(new CanonicalType("http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core"));
                cs.setImplementationGuide(supportedIGList);

                // 3. Drill down and manually force the profile declaration for Patient
                List<CanonicalType> supportedProfiles = new ArrayList<>();
                supportedProfiles.add(new CanonicalType("http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"));

                cs.getRestFirstRep().getResource().stream().filter(r -> "Patient".equals(r.getType()))
                        .forEach(r -> {
                            r.setProfile("http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient");
                            r.setSupportedProfile(supportedProfiles);
                        });
                return cs;
            }
        };

        servlet.setServerConformanceProvider(metadataProvider);
        servlet.registerInterceptor(validatingInterceptor);
        servlet.registerInterceptor(customSecurityInterceptor);

        ServletRegistrationBean<RestfulServer> registration = new ServletRegistrationBean<>(servlet, "/fhir/*");
        registration.setName("HAPI-FHIR-Servlet");

        return registration;
    }
}